# Generated by Django 4.1 on 2023-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('Yield', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('precipitation', models.FloatField(default=0.0)),
                ('cultivated_areas', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvoc', models.IntegerField()),
                ('eco2', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('indoorAirQuality', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
