# Generated by Django 4.1 on 2023-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('model', models.CharField(max_length=10)),
                ('serial', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Images/')),
                ('acquisition_date', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('date', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvoc', models.IntegerField()),
                ('eco2', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('air_quality', models.IntegerField()),
                ('date', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvoc', models.IntegerField()),
                ('eco2', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('air_quality', models.IntegerField()),
                ('date', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='indoorAirQuality',
            new_name='air_quality',
        ),
    ]
