# Generated by Django 4.1 on 2023-07-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device_image_sensor1_sensor2_sensor3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='acquisition_date',
            new_name='date',
        ),
    ]
