# Generated by Django 4.1 on 2023-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
