# Generated by Django 4.1 on 2023-07-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_sensordata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor1',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor2',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor3',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
